server:
  port: 8999
  session:
    timeout: 10
  error:
    path: /error

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/kanban
    username: postgres
    password: xadmin

