server:
  port: 8999
  session:
    timeout: 10

  error:
    path: /error
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/${security.mongodb.password}
logging:
  file: logs/myapplication.log

